version: "3.8"
services:
  dotnetapi:
    build:
      context: "./BookABite_backend"
      dockerfile: Dockerfile
    ports:
      - 8080:8080
    restart: unless-stopped
    #links:
     # - db
    depends_on:
      - db
  db:
    image: postgres:latest
    restart: always
    environment:
      - POSTGRES_DB=postgres
      - POSTGRES_USER=docker
      - POSTGRES_PASSWORD=docker
    ports:
      - 5433:5432
    volumes:
      - db-data:/var/lib/postgresql/data
  seq:
    image: datalust/seq:latest
    environment: 
      - ACCEPT_EULA=Y
    ports:
      - 5341:5341
      - 8081:80
volumes:
  db-data:
#networks:
  #default:
    #driver: bridge