version: "3.8"
services:
  dotnetapi:
    build:
      context: "./BookABite_backend"
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
    restart: unless-stopped
    links:
      - db
  db:
    image: postgres:latest
    restart: always
    environment:
      - POSTGRES_DB=docker
      - POSTGRES_USER=docker
      - POSTGRES_PASSWORD=docker
    ports:
      - 5432:5432
    #volumes:
     # - ./BookABite_database/data:/var/lib/postgresql/data
